apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kube-{{PROFILE}}-nfs
  namespace: kube-{{PROFILE}}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: {{STORAGE}}