apiVersion: v1
kind: Service
metadata:
  name: {{MICROSERVICE}}
  namespace: kube-{{PROFILE}}
spec:
  type: NodePort
  selector:
    app: {{MICROSERVICE}}
  ports:
  - port: {{PORT}}
    nodePort: {{NODE_PORT}}
    targetPort: {{TARGET_PORT}}
    protocol: TCP
