apiVersion: v1
kind: PersistentVolume
metadata:
  name: kube-{{PROFILE}}-nfs
  namespace: kube-{{PROFILE}}
spec:
  capacity:
    storage: {{STORAGE}}
  accessModes:
    - ReadWriteMany
  nfs:
    server: {{NFS_SERVER}}
    path: "{{NFS_PATH}}"